name: BendingItems
author: Simplicitee
api-version: 1.20
version: 1.9.1
main: me.simplicitee.project.items.ItemsPlugin
depend: [ProjectKorra]
permissions:
  bending.items:
    default: op
    children:
      bending.command.item.give: true
      bending.command.item.gui: true
      bending.command.item.equip: true